# DO NOT CHANGE the "init" and "install" sections below

platform:
  - x86

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'


install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_r dplyr
  - travis-tool.sh install_r ggplot2
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits


# Adapt as necessary starting from here

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true
    R_CHECK_ARGS: --no-manual --as-cran --install-args=--build _R_CHECK_CRAN_INCOMING_=TRUE


  matrix:
  - R_VERSION: stable
    R_ARCH: x64

  - R_VERSION: patched
    R_ARCH: x64

  - R_VERSION: devel
    R_ARCH: x64

